HinodeXRT/xrtpy

setup.cfg

The problems building the documentation is probably from an incompatibility that I've run into before with Sphinx 3.0.0 and more recent not be compatible with the way things are being done here.

Specify maximum version of Sphinx

---

.github/workflows/testing.yml
pyproject.toml
setup.cfg
setup.py
tox.ini

This pull request experiments with using versions of `tox.ini` and `testing.yml` that were modified from how they were set up in PlasmaPy.  If this doesn't work then I'll look into this more closely.
The PlasmaPy license is being added separately in #16 but would need to be included if this PR is merged.
Closes #7

Expand test performed by GitHub Actions

---

.github/workflows/testing.yml
pyproject.toml
requirements.txt
requirements/build.txt
requirements/docs.txt
requirements/extras.txt
requirements/install.txt
requirements/tests.txt
setup.cfg
tox.ini

This pull request adopts the configuration for requirements that is being used in PlasmaPy.  The requirements are split into different files in the `requirements` directory.  For example, `requirements/install.txt` has the requirements for installation, `tests.txt` for tests, and so on.  The top-level `requirements.txt` file doesn't list requirements directly, but rather uses the requirements that are defined in these other files.  The requirements also need to be defined in the `setup.cfg` and `pyproject.toml` project configuration files, so I added them there too.

Reorganize package requirements

---

xrtpy/response/channel.py
xrtpy/response/temperature_response.py
xrtpy/response/tests/test_channel.py

Updating CCD gain port right value to 57.5 e-.  Genx file used to create Channel (genx file)  has hard code value of 59.09 e- for CCD right gain. Explained by @kreevescfa, 57.5 e- is the true value to the right port gain, reference the camera paper (https://ui.adsabs.harvard.edu/abs/2008SoPh..249..263K/abstract). GR [e−/DN] = 59.1 + 0.026 T [◦C]. The camera is ran at -60C, so from this formula, the gain is 57.5 -e/DN.

Updated CCD gain right port value.

---

.pre-commit-config.yaml
pyproject.toml

There were a couple of issues related to pre-commit and codespell that came up in #89.  This PR:
- Apply a fix to the pre-commit hook for codespell so that the configuration from `pyproject.toml` can be read in
- Add `te` to list of ignore words in codespell
- Have end-of-file-fixer ignore `.fits` files (and maybe some others)

Update pre-commit and codespell

---

docs/_substitutions.rst

Following up on a suggestion for #89, this PR updates some reST substitutions, including for `|Map|`.  There are also some substitutions which still used `PlasmaPy/PlasmaPy`.

Update reStructuredText substitutions

---

requirements/docs.txt
setup.cfg

This is to fix an issue with the formatting of the example notebook galleries.  See https://github.com/PlasmaPy/PlasmaPy/pull/1654 for details.

Add upper limit to version of sphinx-gallery

---

changelog/102.doc.rst
changelog/104.removal.rst
changelog/111.bugfix.rst
changelog/128.doc.rst
changelog/89.feature.rst
changelog/94.doc.rst
docs/changelog/0.2.0.rst
docs/changelog/index.rst

In the top-level directory, I ran:
```bash
towncrier build --version=0.2.0
```
That created `CHANGELOG.rst` at the top-level. Then I did:
```bash
mv CHANGELOG.rst docs/changelog/0.2.0.rst
```
and added `0.2.0` to the `toctree` in `docs/changelog/index.rst`.  Might also need to remove `dev` from that too, but hopefully not.

Build changelog for 0.2.0 release

---

.pre-commit-config.yaml
pyproject.toml
xrtpy/__init__.py
xrtpy/response/channel.py
xrtpy/response/tests/test_channel.py
xrtpy/response/tests/test_effective_area.py
xrtpy/response/tests/test_temperature_response.py
xrtpy/response/tests/test_temperature_response_coronal.py
xrtpy/response/tests/test_temperature_response_hybrid.py
xrtpy/response/tests/test_temperature_response_photospheric.py
xrtpy/response/tests/test_xrt_teem.py
xrtpy/response/xrt_teem.py
xrtpy/util/__init__.py
xrtpy/util/tests/test_xrt_deconvolve.py
xrtpy/util/xrt_deconvolve.py

[`ruff`](https://beta.ruff.rs/docs/) is a new Python linter, which is really fast because it is written in Rust instead of Python.  `ruff` has a bunch of linter rules for `flake8` already built in, plus the rules for a lot of `flake8` extensions.  Unlike `flake8`, `ruff` is able to automagically fix a wide variety of linter errors.  In the future, we should be able to drop `flake8` and use `ruff` instead.
This PR adds a pre-commit hook for `ruff`, and makes some automatic fixes.

Add `ruff` to `pre-commit`

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/general_issue.yml

This PR adapts templates from PlasmaPy for creating issues. To get a preview of how these would work, check out the [new issue page for PlasmaPy](https://github.com/PlasmaPy/PlasmaPy/issues/new/choose).

Add GitHub issue templates

---

.readthedocs.yaml
docs/examples.rst

Our Read the Docs configuration became out-of-date and stopped working. This PR copies over some YAML magic from PlasmaPy's RTD config file to make things work again.

Update Read the Docs configuration file

---

xrtpy/util/tests/test_xrt_remove_lightleak.py
xrtpy/util/xrt_remove_lightleak.py

This PR removes the light-leak files from the repository in favor of pulling them from one of two possible solarsoft mirrors with the goal of reducing the total size of the repository. It also significantly refactors the light-leak removal function.
At a high-level, the changes to the light-leak function are:
- If it is passed to the function, the light-leak array must now be a `sunpy.map.Map` object, not just a bare array
- The custom`rebin` function has been removed in favor of just calling `Map.resample` to the resolution of the input map. My understanding is that this is basically what was being achieved by rebinning from 1024 to 2048 and then dividing by 4.
- `leak_image` is now called `leak_map` to reflect the fact that it is a `sunpy.map.Map`, not just a bare array
- `k_fact` is …

Refactor light-leak function and remove light-leak files from repository

---

docs/changelog/0.4.0.rst
docs/changelog/index.rst
docs/conf.py

Updating the XRTpy changelog files to include the latest changes for the upcoming version 0.4.0 release.

Build changelog for 0.4.0 release

---

.github/workflows/testing.yml
.gitignore
docs/notebooks/data_analysis/Deconvolving_XRT_images.ipynb
docs/notebooks/data_analysis/Remove_lightleak.ipynb
requirements/docs.txt
setup.cfg

This PR is to address the following error that started showing up multiple times in our documentation builds:
```
/home/runner/work/xrtpy/xrtpy/docs/notebooks/data_analysis/Deconvolving_XRT_images.ipynb:137: ERROR: Content block expected for the "raw" directive; none found.
```
I was able to resolve the error by requiring `nbconvert < 7.14`.  I also tried changing the OS in the GitHub Action from `ubuntu-latest` to `macos-latest` and upgrading to the most recent version of `pandoc`, but neither of those changes got rid of the error.

Set upper limit on version of `nbconvert`

---

requirements/docs.txt

This should mean you get pretty progress bars and no warnings in your docs builds.

Add ipywidgets to docs requirements

---

docs/notebooks/data_analysis/Deconvolving_XRT_images.ipynb

This PR updates the import method for SunPy maps in the Deconvolving_XRT_images.ipynb notebook to align with the way it's imported in other notebooks, consistency. Addressing issue #237 .

Updated notebook with improved sunpy map import method

---

docs/api_static/xrtpy.image_correction.deconvolve.rst
docs/api_static/xrtpy.image_correction.rst
docs/api_static/xrtpy.response.temperature_response.rst
docs/api_static/xrtpy.util.make_exposure_map.rst
docs/api_static/xrtpy.util.rst
docs/api_static/xrtpy.util.time.rst
xrtpy/image_correction/__init__.py
xrtpy/image_correction/_ssw_mirrors.py
xrtpy/image_correction/deconvolve.py
xrtpy/image_correction/remove_lightleak.py
xrtpy/util/__init__.py
xrtpy/util/make_exposure_map.py

This PR adds documentation stub files to `docs/api_static` to make sure that the modules show up in the documentation. The purpose of these stub files is to make sure that every module in `xrtpy` has a corresponding [`automodapi`](https://sphinx-automodapi.readthedocs.io/en/latest/automodapi.html) directive.  
More information on how and why to do this is in the [PlasmaPy doc guide](https://docs.plasmapy.org/en/latest/contributing/doc_guide.html#creating-a-documentation-stub-file-for-a-new-module). 
> [!NOTE]
> If we decide to create narrative documentation pages for the different subpackages at `docs/response.rst`, we'd need to delete the corresponding file in `docs/api_static/`.

Create documentation stub files

---

.github/workflows/testing.yml

Previously, we've been splitting up tests.  We ran the `initial-tests` first, and then the `comprehensive-tests` afterwards if the `initial-tests` pass.
This PR consolidates the initial and comprehensive tests so that we don't need to wait as long for all of the tests to finish.
I also am updating the names of the test sessions to be more consistent with the naming scheme in use for PlasmaPy.  If the renaming gets merged, we'll need to update the names of required tests for pull requests.

Consolidate initial and comprehensive tests

---

.pre-commit-config.yaml
pyproject.toml

- Ran `pre-commit autoupdate` so that XRTpy is using the most recent versions of pre-commit hooks (including ruff)
- Ignored rule PLC2401 for non-ascii characters in names. My personal view is that it's okay to include non-ascii characters in names when there's a good reason to, and when users don't have to interact with it.

Update pre-commit configuration

---

docs/CODE_OF_CONDUCT.rst
docs/index.rst

Creating a Code of Conduct for the XRTpy project. The Code of Conduct is adapted from the Contributor Covenant (https://www.contributor-covenant.org/) and is designed to foster a welcoming and inclusive community for all contributors and users of XRTpy.  Addresses and resolves the issues discussed in Issue #10  - Add a Code of Conduct. Furthermore, a step towards meeting the requirements to become a SunPy-affiliated package, as outlined in [sunpy/sunpy.org issue #431](https://github.com/sunpy/sunpy.org/issues/431).

Add Code of Conduct to XRTpy

---

docs/contributing/installation_for_development.rst
requirements.txt

In some pull requests earlier to consolidate requirements in `pyproject.toml`, I ended up removing the requirements directory but not `requirements.txt`.  This PR finishes what I started, and removes `requirements.txt` since it is no longer used in CI.

Remove requirements.txt

---

.pre-commit-config.yaml
docs/notebooks/data_analysis/Remove_lightleak.ipynb
xrtpy/image_correction/tests/test_deconvolve.py

Fixes #238 
This also reorganizes and simplifies the deconvolution tests.

Remove use of deprecated `pkg_resources`

---

.github/workflows/testing.yml
.gitignore
noxfile.py
pyproject.toml
xrtpy/image_correction/tests/test_remove_lightleak.py

The proposed community standard in [SPEC 0](https://scientific-python.org/specs/spec-0000/) is that versions of Python released in the last three years should be supported by the scientific Pythoniverse.  Python 3.9 was released almost four years ago, so we can drop XRTpy support for it.

Drop support for Python 3.9

---

xrtpy/response/temperature_from_filter_ratio.py

Add comments to the temperature_from_filter_ratio.py script to explain the logic behind the temperature interpolation equation. Help clarify the purpose of variables a and b, which represent the differences between the observed and model filter ratios, and describe how the equation ensures smooth temperature transitions by weighing adjacent temperature values proportionally.  Addressing Issue #269 .

Add comments to explain temperature interpolation in temperature_from_filter_ratio.py

---

.readthedocs.yaml
xrtpy/response/temperature_from_filter_ratio.py

Updating file required by sphinx: The sphinx.configuration key is missing. This key is now required, see the [blog post](https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/) for more information.

Fix ReadTheDocs build by adding sphinx.configuration

---

noxfile.py
xrtpy/response/temperature_from_filter_ratio.py

In #330, we were getting `SunPyDeprecationWarning`s when using the most recent version of SunPy in documentation builds (see #327).  To temporarily alleviate this, I added an `--exclude-newer` flag that is invoked by `uv` when installing packages for the doc builds. This flag prevents dependency resolutions from including packages that were added after a particular date in the environment.
This PR removes the `--exclude-newer` flag, which will allow the most recent versions of dependencies to be used in the Python environments for documentation builds. The deprecation warning is still happening, so this PR is mostly a placeholder so that we don't forget about it later on.  This PR should only be merged when the documentation build is passing.

Allow most recent versions of dependencies to be used in documentation builds
