HinodeXRT/xrtpy

- .github/workflows/testing.yml
- requirements.txt
- setup.cfg
- xrtpy/tests/test_example.py
I added NumPy, Astropy, and SunPy as required packages.  Since we're just starting development, I put recent pretty recent versions of Astropy and SunPy since these will be older versions once we get a few development releases in.  I also added a few more metadata fields, loosely following the example of PlasmaPy's `setup.cfg` file.
> Update requirements and setup configuration

- .github/workflows/stale.yml
- licenses/PlasmaPy_license.md
This commit adds a GitHub Action that checks for pull requests that have not had any activity for the past six months.  If there was no activity, and no changes after a 14 day grace period, the pull request will automatically be closed.  If needed, pull requests could be re-opened after they were closed.
> Create GitHub Action to close dormant pull requests

- .pre-commit-config.yaml
This PR adds the pre-commit configuration file from PlasmaPy, updated to the most recent release of `black`.
> Add a pre-commit configuration

- .codecov.yaml
This adds `.codecov.yaml` for [Codecov](https://about.codecov.io/).
> Add Codecov configuration file

- xrtpy/__init__.py
- xrtpy/response/effective_area.py
- xrtpy/response/temperature_response.py
- xrtpy/response/tests/test_channel.py
- xrtpy/response/tests/test_effective_area.py
- xrtpy/response/tests/test_temperature_response.py
This PR applies some refactorings from [Sourcery](https://sourcery.ai) which is a framework that looks for common patterns in Python code and applies simplifying refactorings.
> Apply automated refactorings from Sourcery

- docs/bibliography.bib
- docs/getting_started.rst
This page will contain documentation about XRTpy.
> Getting Started

- .github/workflows/testing.yml
- .pre-commit-config.yaml
- README.md
- docs/index.rst
- setup.cfg
- xrtpy/response/effective_area.py
- xrtpy/response/tests/test_effective_area.py
- xrtpy/response/tests/test_temperature_response.py
This purpose of this PR is to make a few miscellaneous updates to packaging, metadata, and documentation.  
I'm also doing this PR to check that my previous PRs didn't break anything.
> Make minor updates to packaging and documentation

- xrtpy/util/time.py
Updating epoch to astropy.time.Time as done by [wtbarnes:fix-tresp-tests](https://github.com/wtbarnes/xrtpy/tree/fix-tresp-tests).
> Updating epoch to astropy.time.Time

- setup.cfg
Updating the options.package_data in the setup.cfg file as done by @wtbarnes in pull request https://github.com/HinodeXRT/xrtpy/pull/99.
> Updating package data in setup.cfg

- .pre-commit-config.yaml
- docs/notebooks/channel.ipynb
- docs/notebooks/computing_functions/temperature_response.ipynb
- xrtpy/response/temperature_response.py
- xrtpy/response/tests/test_channel.py
- xrtpy/response/tests/test_effective_area.py
- xrtpy/response/tests/test_temperature_response.py
This PR updates the versions of packages used by pre-commit to the ones most recently available, and will apply any associated formatting changes.
> Update pre-commit configuration

- .github/workflows/testing.yml
- docs/examples.rst
- xrtpy/response/channel.py
- xrtpy/response/effective_area.py
When transitioning the test runner from `tox` to `nox`, it looks like I inadvertently left out the test environment for building the documentation.  The test documentation build on Read the Docs has still been working, though.  This PR adds the test environment for building the documentation.
> Add documentation tests into test suite

- .readthedocs.yaml
Copied over directly from PlasmaPy
> Update the Read the Docs configuration file

- docs/changelog/0.3.0.rst
- docs/changelog/index.rst
Updated the XRTpy changelog files to hold the newest file for version three release.
> Build changelog for 0.3.0 release

- xrtpy/response/temperature_response.py
- xrtpy/response/tests/test_temperature_response.py
- xrtpy/response/tests/test_temperature_response_coronal.py
- xrtpy/response/tests/test_temperature_response_hybrid.py
- xrtpy/response/tests/test_temperature_response_photospheric.py
The path to the model for hybrid abundances and photospheric abundances were switched.
> Fix paths to spectral model files in temperature response

- docs/about_xrt.rst
- docs/examples.rst
- docs/getting_started.rst
- docs/glossary.rst
The purpose of this pull request is to update and review all the text/documentation sections of XRTpy. This includes making necessary revisions and improvements to ensure the accuracy, clarity, and completeness of the documentation.
> scrutinize documentation 

- xrtpy/util/xrt_deconvolve.py
Use sunpy data manager to download the data files needed to use xrt_deconvolve.
> Download data files

- xrtpy/util/__init__.py
- xrtpy/util/xrt_deconvolve.py
This PR adds multiple SSW mirrors when checking where to download the PSF files from.
> Check multiple SSW mirrors for remote psf files

- xrtpy/util/time.py
Removing used function in time.py.
> Removing unused function

- docs/conf.py
Fixing an error I'm getting across all PRs.
> Add the nbsphinx_allow_errors option

- joss/paper.bib
- joss/paper.md
Addressing JOSS reviews about the xrtpy paper references: References #232
> Corrections to JOSS References

- docs/notebooks/data_analysis/Using_temperature_from_filter_ratio.ipynb
- setup.cfg
Fixing Installation issues #228
> Addressing JOSS installation issues

- xrtpy/response/temperature_response.py
Addressing review from issue #230 , JOSS reviewers. Working to update all xrtpy functions/methods/attributes to have documentation.
> Functionality documentation Update - temperature response

- docs/install.rst
Adding zsh doc method, addressing issue #229
> Installation instructions update

- docs/conf.py
- xrtpy/response/channel.py
Addressing review from issue https://github.com/HinodeXRT/xrtpy/issues/230 , JOSS reviewers. Working to update all xrtpy functions/methods/attributes to have documentation - script for this PR is for the Channel.
> Functionality documentation Update - Channel

- xrtpy/response/effective_area.py
Addressing review from issue #230 , JOSS reviewers. Working to update all xrtpy functions/methods/attributes to have documentation - script for this PR is for the effective area.
> Functionality documentation Update - Effective Area 

- joss/paper.bib
Updating the final changes for the XRTpy JOSS paper submission -PART 4- Correction to Sunpy name reference - https://github.com/openjournals/joss-reviews/issues/6396#top.
> Final Updates for XRTpy JOSS Submission - Part 4

- docs/glossary.rst
This pull request introduces a series of updates to the XRTpy glossary page, adding new key terms and detailed definitions that are crucial for users and developers working with the X-Ray Telescope (XRT) data. The aim is to enhance clarity and provide valuable context for existing and prospective users of the XRTpy library.
> Update Glossary with New Terms and Definitions for XRTpy

- docs/contributing/acknowledging_xrtpy.rst
- docs/contributing/index.rst
Providing guidelines for users to properly cite and acknowledge XRTpy in their scientific works and presentations.
> Add Citation Section to Documentation for XRTpy

- IDL_scripts/IDL_test_scripts/get_xrt_test_effective_area.pro
- IDL_scripts/IDL_test_scripts/get_xrt_test_temperature_response.pro
> Updated IDL script to work for two filter
